name: Update resource pack

on:
  schedule:
    - cron: "30 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Update language files
        run: |
          git submodule sync
          git submodule update --remote --recursive --force

      - name: Update resource pack
        run: uv run pack.py

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: update language files"

      - name: Get Minecraft version
        run: |
          cd mc_lang
          cat version.txt
          echo "ver=$(<version.txt)" >> "$GITHUB_ENV"

      - name: Check if Modrinth version exists
        run: |
          url="https://api.modrinth.com/v2/project/atOcnEWk/version/${{ env.ver }}"
          resp=$(curl --silent "$url")
          if echo "$resp" | grep -q '"version_number"'; then
            echo "MODRINTH_EXISTS=true" >> "$GITHUB_ENV"
            echo "Modrinth version exists, will skip upload."
          else
            echo "MODRINTH_EXISTS=false" >> "$GITHUB_ENV"
            echo "Modrinth version does not exist, will upload."
          fi

      - name: Release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: ${{ env.ver }}
          files: unreadable_language_pack.zip
          name: ${{ env.ver }}
          version: ${{ env.ver }}

      - name: Upload to Modrinth
        if: env.MODRINTH_EXISTS != 'true'
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: atOcnEWk
          version: ${{ env.ver }}
          loaders: minecraft
          game-versions: |-
            1.21.x
            1.20.x
            1.19.4
            1.19.3
          files: unreadable_language_pack.zip
